### ISSUE TITLE
Old: Link Suggestions

### ISSUE THREAD

**Issue by michidk** [michidk/Unity-Script-Collection#1]
- [x] https://twitter.com/chriswade__/status/776184020061356033
- [x] https://github.com/adamgit/Unity-delaunay

**Comment by michidk** [comment]
- [x] http://designagame.eu/2016/09/is-unity-webgl-loading-a-simple-fix/
- [x] https://github.com/aphex-/BrotherhoodOfNode/blob/master/README.md
- [x] https://www.assetstore.unity3d.com/en/#!/content/53869

**Comment by michidk** [comment]
added in 0fd902c4b731451b63a0d271a10466b07df520ca

**Comment by michidk** [comment]
- [x] https://twitter.com/unity3d/status/780812894502084609
- [x] https://github.com/keijiro/SkyboxPlus
- [x] https://github.com/sabresaurus/SabreCSG
- [x] https://github.com/LostPolygon/ConstantsGeneratorKit
- [x] https://gist.github.com/michidk/3b49362e21563a1d66d52f4cf4bdc7ce
- [x] https://gist.github.com/jbevain/a982cc580fb796c93e4e
- [x] https://twitter.com/mrpodunkian/status/715309192886624256
- [x] https://github.com/hecomi/uDesktopDuplication
- [x] https://github.com/Chman/SMAA
- [x] https://www.assetstore.unity3d.com/en/?&_ga=1.224491866.1155275539.1473983191#!/content/10144
- [x] https://github.com/rlabrecque/Steamworks.NET
- [x] https://github.com/Facepunch/Facepunch.Steamworks

**Comment by michidk** [comment]
https://github.com/sabresaurus/SabreCSG

**Comment by michidk** [comment]
- [x] https://github.com/thestonefox/VRTK
- [x] https://github.com/slipster216/VertexPaint
- [x] https://github.com/SixWays/FacePaint
- [x] https://github.com/GabeBigBoxVR/UnityDefaultMicrophone
- [x] https://github.com/StompyRobot/stateless
- [x] https://gist.github.com/Skybladev2/d0d029716b1651cc1947
- [x] https://github.com/traggett/UnitySpriteShaders
- [x] https://github.com/toinfiniityandbeyond/unity-tilemap
- [x] https://github.com/thinksquirrel/asset-store-batch-mode
- [x] https://github.com/NormalVR/CutieKeys/
- [x] https://github.com/FeNo/InGameReplay
- [x] https://github.com/bbbscarter/UberLogger
- [x] https://github.com/nicoplv/smart-layers
- [x] https://github.com/Unity-Technologies/PostProcessing
- [x] https://github.com/aschearer/unitysizeexplorer
- [x] http://pastebin.com/4KGd4LHb / https://twitter.com/minionsart/status/833706337016115201

**Comment by michidk** [comment]
- [x] https://www.assetstore.unity3d.com/en/#!/content/79898
- [x] https://github.com/sschmid/Entitas-CSharp
- [x] https://github.com/BrokenVector/LowPolyShaders
- [x] https://github.com/BrokenVector/BetterUnityScriptTemplates
- [x] https://github.com/madsbangh/EasyButtons
- [x] https://github.com/kimsama/Unity-NGUIExtension
- [x] https://github.com/kimsama/unity3d-webview-csharp
- [x] https://oc.unity3d.com/index.php/s/dfc9aa1491ff905f589408aa136eab23
- [x] https://github.com/rjth/Punchkeyboard
- [x] https://bitbucket.org/UnityUIExtensions/unity-ui-extensions
- [x] https://github.com/aestheticinteractive/Hover-UI-Kit
- [x] https://github.com/Unity-Technologies/VRLineRenderer
- [x] https://github.com/MattRix/UnityDecompiled
- [x] https://www.assetstore.unity3d.com/en/#!/content/84074
- [x] https://github.com/ChemiKhazi/Sprytile
- [x] https://github.com/jknightdoeswork/gpu-physics-unity
- [x] https://gist.github.com/nicoplv/df3368eb38849a3f76a97fc27ba8ca62
- [x] https://www.assetstore.unity3d.com/en/#!/content/84074
- [x] https://github.com/sunilnayak133/ikccd
- [x] https://github.com/falconmick/ClearFlagsMobile

**Comment by kimsama** [comment]
- [x] https://github.com/kimsama/Unity-QuickSheet

**Comment by michidk** [comment]
- [x] https://github.com/MangoSister/SPHFluid
- [x] https://github.com/Demigiant/demilib
- [x] https://github.com/toofu37/twitter-for-unity
- [x] https://github.com/haydenjameslee/UnityRefChecker
- [x] https://github.com/larsbertram69/Lux-2.02-Personal
- [x] https://github.com/Seneral/Node_Editor
- [x] https://github.com/neuecc/UniRx
- [x] https://github.com/Unity-Technologies/DeLightingTool
- [x] https://github.com/keijiro/Lasp
- [x] https://github.com/Real-Serious-Games/Unity-Scene-Query
- [x] https://github.com/mattatz/unity-lut-generator
- [x] https://github.com/Chaser324/unity-wireframe

**Comment by sirgru** [comment]
Suggestions:
- [x] [Simple Editor Shortcuts Tools Collection](https://bitbucket.org/sirgru/simple-editor-shortcuts-tools-collection)
- [x] [Ring Buffer Data Structure](https://bitbucket.org/sirgru/ring_buffer)
- [x] [Mesh Combine Wizard](https://bitbucket.org/sirgru/meshcombinewizard)

**Comment by michidk** [comment]
- [x] https://github.com/aschearer/unitysizeexplorer
- [x] https://github.com/Unity-Technologies/2d-extras
- [x] https://github.com/MicroGSD/RoadArchitect
- [x] https://github.com/keijiro/KinoBinary
- [x] https://github.com/andydbc/HologramShader
- [x] https://github.com/MephestoKhaan/UnityEventVisualizer
- [x] http://diegogiacomelli.com.br/unity3d-scenepreview-inspector/
- [x] https://github.com/kimsama/Unity-QuickSheet

**Comment by willnode** [comment]
- [x] https://github.com/sonicether/SEGI

**Comment by XpycT** [comment]
- [x] https://github.com/Siccity/xNode

**Comment by michidk** [comment]
- [x] https://github.com/Kink3d/SimpleTraffic
- [x] https://github.com/raphael-ernaelsten/Aura

**Comment by CodeDoes** [comment]
- [x] https://github.com/Scrawk/Hull-Delaunay-Voronoi

**Comment by hitorijanai** [comment]
- [x] https://github.com/kayac/kamakura-shaders/

**Comment by Strepto** [comment]
- [x] https://github.com/Unity-Technologies/UnityCsReference

**Comment by michidk** [comment]
- [x] https://github.com/Unity-Technologies/vector-graphics-samples
- [x] https://github.com/Chman/Typogenic
- [x] https://github.com/raphael-ernaelsten/Aura
- [x] https://github.com/Facepunch/Facepunch.Highlight

**Comment by Patroklo** [comment]
I have a more current stateles machine than the one you are linking:

- [ ] https://github.com/Patroklo/stateless

It should have a couple of new features and solved bugs.

**Comment by keenanwoodall** [comment]
- [ ] [Deform](https://github.com/keenanwoodall/Deform) - A framework for deforming meshes in the editor and at runtime in Unity.

**Comment by KonH** [comment]
- [ ] https://github.com/KonH/UDBase

**Comment by ghost** [comment]
KeyBound

- [ ] http://github.com/norseware/KeyBound

A simple input and key binding asset to let players map their own controls.

**Comment by fx-lange** [comment]
RecordAndRepeat

Recording and playback of custom data via Unity Timeline

- [ ] https://github.com/fx-lange/unity-record-and-repeat

**Comment by michidk** [comment]
- [ ] https://github.com/pandr/unity-debug-overlay
- [ ] https://github.com/Habrador/Self-driving-vehicle

**Comment by michidk** [comment]
Closing this for now. From now on, only pull requests are accepted as contributions (see CONTRIBUTE file).

EDIT: A lock is probably more sufficient, since the recent links are not yet in the list.
