### ISSUE TITLE
Add Additional Unity Script Repos

### ISSUE THREAD

**Issue by Nesh108** [michidk/Unity-Script-Collection#14]
Hello,

I stumbled upon this nice collection of unity scripts and I thought I would like to contribute with some little things I worked on:

- **Unity 2.5D Destruction** ([GitHub](https://github.com/Nesh108/Unity-2.5D-Destruction) - [Unity Forums](https://forum.unity.com/threads/free-open-source-unity-2-5d-destruction.545216/)): I have forked the already available Unity-2D-Destruction and added extra functionality to support 2.5D games (such as 3D colliders, 3D rigidbodies, etc.).
- **Unity MetaBalls Liquids** ([GitHub](https://github.com/Nesh108/Unity_MetaBalls_Liquids) - [Unity Forums](https://forum.unity.com/threads/free-open-source-simple-liquid-simulation-with-metaballs.556858)): I needed to have a very simple "thick fluid" simulation, such as honey or goo, to work with gravity and surfaces. So I extended the Unity MetaBalls script ([link](https://wiki.unity3d.com/index.php?title=MetaBalls)), cleaned it up and added some features.

And thanks for maintaining such a useful list :)

/Nesh

**Comment by michidk** [comment]
Hey Nesh,

going to add it as soon as I find the time. The fastest way is always to simply create a pull request.

Thanks,
Michael

**Comment by michidk** [comment]
Done in https://github.com/michidk/Unity-Script-Collection/pull/21
