### ISSUE TITLE
MyBox — collection of attributes, extensions, types and features for Unity

### ISSUE THREAD

**Issue by andrumak** [michidk/Unity-Script-Collection#16]
[https://github.com/Deadcows/MyBox](https://github.com/Deadcows/MyBox)

I started to write my own collection of stuff in 2015 and now it's pretty big and have some very useful bits.
Recently I started to fill up documentation for stuff in MyBox so now it fit's this list well :)

I guess it should be in Other section

**Comment by michidk** [comment]
Please submit single scripts and no script collections.
