### ISSUE TITLE
Please reopen link suggestions

### ISSUE THREAD

**Issue by nukadelic** [michidk/Unity-Script-Collection#28]
please reopen for ease and mobile usage, here are two of my repos i would like to share ( screenshots and info available ) 

https://github.com/nukadelic/Unity-Scene-Picker
https://github.com/nukadelic/Unity-Lightmap-Prefab-Baker

**Comment by michidk** [comment]
Please create a pull request. 
   
  
  
   
    Nukadelic <
    notifications@github.com> hat am 11. März 2020 03:08 geschrieben:
   
   
    
   
   
    
   
   
    please reopen for ease and mobile usage, here are two of my repos i would like to share ( screenshots and info available )
   
   
    
   
   
    https://github.com/nukadelic/Unity-Scene-Picker
    
   
   
    https://github.com/nukadelic/Unity-Lightmap-Prefab-Baker
    
   
   
    
   
   
    --
   
   
    You are receiving this because you are subscribed to this thread.
   
   
    Reply to this email directly or view it on GitHub:
   
   
    https://github.com/michidk/Unity-Script-Collection/issues/28

**Comment by michidk** [comment]
Link suggestions are made through pull requests and not issues. Please read https://github.com/michidk/Unity-Script-Collection/blob/master/CONTRIBUTING.md
